######################################################################
#
# File name : led_ctrl_3_tb_compile.do
# Created on: Thu Mar 07 18:12:04 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/work
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../led_ctrl_3.srcs/sources_1/new/led_ctrl_3.v" \
"../../../../led_ctrl_3.srcs/sim_1/new/led_ctrl_3_tb.v" \


# compile glbl module
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

