######################################################################
#
# File name : led_ctrl_3_tb_simulate.do
# Created on: Thu Mar 07 18:12:06 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.led_ctrl_3_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {led_ctrl_3_tb_wave.do}

view wave
view structure
view signals

do {led_ctrl_3_tb.udo}

run 1000ns
