######################################################################
#
# File name : led_ctrl_3_tb_wave.do
# Created on: Thu Mar 07 15:55:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
