set_property IOSTANDARD LVCMOS33 [get_ports {switch_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports dio_o]
set_property IOSTANDARD LVCMOS33 [get_ports rclk_o]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_i]
set_property IOSTANDARD LVCMOS33 [get_ports srclk_o]
set_property PACKAGE_PIN AB21 [get_ports {switch_i[0]}]
set_property PACKAGE_PIN AB22 [get_ports {switch_i[1]}]
set_property PACKAGE_PIN L5 [get_ports clk_i]
set_property PACKAGE_PIN AA16 [get_ports dio_o]
set_property PACKAGE_PIN AA17 [get_ports rclk_o]
set_property PACKAGE_PIN R4 [get_ports reset_n_i]
set_property PACKAGE_PIN AB13 [get_ports srclk_o]

