webtalk_init -webtalk_dir D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.sim/sim_1/behav/xsim/xsim.dir/uart_ram_TFT_send_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 30 14:39:41 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1b9c9735-49c8-424e-bf0f-d627d2d72eb0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0c80a87f6753431487e4ad23d9ee0973" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "44" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "13" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "523 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "44 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "460" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "19" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "117280_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3841690040 -regid "" -xml D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.sim/sim_1/behav/xsim/xsim.dir/uart_ram_TFT_send_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.sim/sim_1/behav/xsim/xsim.dir/uart_ram_TFT_send_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.sim/sim_1/behav/xsim/xsim.dir/uart_ram_TFT_send_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
