# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tft.xdc

# IP: ip/RAM_DISPLAY_1/RAM_DISPLAY.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_DISPLAY || ORIG_REF_NAME==RAM_DISPLAY} -quiet] -quiet
