######################################################################
#
# File name : demo_tb_compile.do
# Created on: Wed Mar 27 11:11:39 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/work
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../imports" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt/example_design/jesd204_0_phy_gt_tx_startup_fsm.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt/example_design/jesd204_0_phy_gt_rx_startup_fsm.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt_init.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt_cpll_railing.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt_gt.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt_multi_gt.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt/example_design/jesd204_0_phy_gt_sync_block.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_block.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_sync_block.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_support.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_gt_common_wrapper.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_gtwizard_0_common.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_clocking.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_support.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_block.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/axi_ipif/jesd204_0_address_decoder.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_register_decode.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/axi_ipif/jesd204_0_axi_lite_ipif.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/axi_ipif/jesd204_0_counter_f.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/axi_ipif/jesd204_0_pselect_f.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/axi_ipif/jesd204_0_slave_attachment.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_count_err.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_reset_block.v" \
"../../../../jesd204_0_ex.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.v" \
"../../../../imports/jesd204_0_example_design.v" \
"../../../../imports/jesd204_0_sig_chk.v" \
"../../../../imports/jesd204_0_transport_layer_demapper.v" \
"../../../../imports/demo_tb.v" \


# compile glbl module
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

