######################################################################
#
# File name : demo_tb_simulate.do
# Created on: Wed Mar 27 11:11:45 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L jesd204_v7_2_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.demo_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {demo_tb_wave.do}

view wave
view structure
view signals

do {demo_tb.udo}

run 1000ns
