######################################################################
#
# File name : demo_tb_wave.do
# Created on: Wed Mar 27 11:11:45 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
