# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL.xci
# IP: The module: 'my_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL.xci
# IP: The module: 'my_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/my_PLL/my_PLL_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
