# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NEW/TYUT/FPGA/Code/3_Test/ch34_acz7015_rom_image_tft_hdmi800x480/rom_image_tft_hdmi.srcs/sources_1/ip/rom_image/rom_image.xci
# IP: The module: 'rom_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/3_Test/ch34_acz7015_rom_image_tft_hdmi800x480/rom_image_tft_hdmi.srcs/sources_1/ip/rom_image/rom_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/NEW/TYUT/FPGA/Code/3_Test/ch34_acz7015_rom_image_tft_hdmi800x480/rom_image_tft_hdmi.srcs/sources_1/ip/rom_image/rom_image.xci
# IP: The module: 'rom_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/3_Test/ch34_acz7015_rom_image_tft_hdmi800x480/rom_image_tft_hdmi.srcs/sources_1/ip/rom_image/rom_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
