# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/jesd204_0.xci
# IP: The module: 'jesd204_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/jesd204_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] -quiet

# IP: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_0_phy_gt || ORIG_REF_NAME==jesd204_0_phy_gt} -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy_gt || ORIG_REF_NAME==jesd204_0_phy_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt_ooc.xdc

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_ooc.xdc

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_clock_group.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/jesd204_0.xci
# IP: The module: 'jesd204_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/jesd204_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] -quiet

# IP: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_0_phy_gt || ORIG_REF_NAME==jesd204_0_phy_gt} -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy_gt || ORIG_REF_NAME==jesd204_0_phy_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/ip_0/jesd204_0_phy_gt_ooc.xdc

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_ooc.xdc

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_clock_group.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/ip_0/synth/jesd204_0_phy_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/2_Exercises/SignalProcessing/JESD/JESD.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
