######################################################################
#
# File name : sim_tb_wave.do
# Created on: Sun Mar 24 18:38:00 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
