######################################################################
#
# File name : sim_tb_compile.do
# Created on: Sun Mar 24 22:14:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/work
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../project_1.srcs/sources_1/ip/axi_full_0/hdl/axi_full_v1_0_M00_AXI.v" \
"../../../../project_1.srcs/sources_1/ip/axi_full_0/hdl/axi_full_v1_0_S00_AXI.v" \
"../../../../project_1.srcs/sources_1/ip/axi_full_0/hdl/axi_full_v1_0.v" \
"../../../../project_1.srcs/sources_1/ip/axi_full_0/sim/axi_full_0.v" \
"../../../../project_1.ip_user_files/bd/design_1/ip/design_1_axi_full_0_0/sim/design_1_axi_full_0_0.v" \
"../../../../project_1.ip_user_files/bd/design_1/ip/design_1_axi_full_1_0/sim/design_1_axi_full_1_0.v" \
"../../../../project_1.ip_user_files/bd/design_1/sim/design_1.v" \
"../../../../project_1.srcs/sources_1/new/AXI_FULL_M_module.v" \
"../../../../project_1.srcs/sources_1/new/TOP.v" \
"../../../../project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v" \
"../../../../project_1.srcs/sim_1/new/sim_tb.v" \


# compile glbl module
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

