# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/NEW/TYUT/FPGA/Project/3_GoldDivision/DDS/dds_ad9767/dds_ad9767.srcs/sources_1/ip/triangular_rom/triangular_rom.xci
# IP: The module: 'triangular_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Project/3_GoldDivision/DDS/dds_ad9767/dds_ad9767.srcs/sources_1/ip/triangular_rom/triangular_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'triangular_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/NEW/TYUT/FPGA/Project/3_GoldDivision/DDS/dds_ad9767/dds_ad9767.srcs/sources_1/ip/triangular_rom/triangular_rom.xci
# IP: The module: 'triangular_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Project/3_GoldDivision/DDS/dds_ad9767/dds_ad9767.srcs/sources_1/ip/triangular_rom/triangular_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'triangular_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
