# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/RAM_DISPLAY/RAM_DISPLAY.xci
# IP: The module: 'RAM_DISPLAY' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/RAM_DISPLAY/RAM_DISPLAY_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_DISPLAY'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/RAM_DISPLAY/RAM_DISPLAY.xci
# IP: The module: 'RAM_DISPLAY' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PL/3_GoldDivision/RGB/uart_ram_tft/uart_ram_tft.srcs/sources_1/ip/RAM_DISPLAY/RAM_DISPLAY_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_DISPLAY'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
