set_property SRC_FILE_INFO {cfile:D:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/gpio_interrupt/gpio_interrupt.srcs/constrs_1/new/gpio_interrupt.xdc rfile:../../../gpio_interrupt.srcs/constrs_1/new/gpio_interrupt.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports {GPIO_0_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P7 [get_ports {GPIO_0_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB12 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {gpio_rtl_1_tri_io[0]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports {gpio_rtl_0_tri_io[1]}]
