# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async.xci
# IP: The module: 'fifo_async' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async.xci
# IP: The module: 'fifo_async' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Project/SilverDivision/fifo_test/fifo_test.srcs/sources_1/ip/fifo_async/fifo_async_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
