######################################################################
#
# File name : dds_ad9767_tb_wave.do
# Created on: Sun Mar 24 14:45:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
