######################################################################
#
# File name : dds_ad9767_tb.udo
# Created on: Sun Mar 24 14:45:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
