######################################################################
#
# File name : dds_ad9767_tb_compile.do
# Created on: Sun Mar 24 15:08:12 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/work
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim/xil_defaultlib
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim/xpm
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_2

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vmap xpm modelsim_lib/msim/xpm
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vmap blk_mem_gen_v8_4_2 modelsim_lib/msim/blk_mem_gen_v8_4_2

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"D:/NEW/TYUT/Vivado/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vcom -64 -93 -work xpm  \
"D:/NEW/TYUT/Vivado/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -64 -incr -work blk_mem_gen_v8_4_2  \
"../../../../dds_ad9767.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../dds_ad9767.srcs/sources_1/ip/triangular_rom/sim/triangular_rom.v" \
"../../../../dds_ad9767.srcs/sources_1/ip/square_rom/sim/square_rom.v" \
"../../../../dds_ad9767.srcs/sources_1/ip/sine_rom/sim/sine_rom.v" \
"../../../../dds_ad9767.srcs/sources_1/imports/new/dds.v" \
"../../../../dds_ad9767.srcs/sources_1/new/dds_ad9767.v" \
"../../../../dds_ad9767.srcs/sources_1/imports/new/key_filter.v" \
"../../../../dds_ad9767.srcs/sim_1/new/dds_ad9767_tb.v" \

# compile glbl module
D:\\NEW\\TYUT\\modelsim10.6\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

