######################################################################
#
# File name : dds_ad9767_tb_simulate.do
# Created on: Sun Mar 24 15:08:15 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L blk_mem_gen_v8_4_2 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.dds_ad9767_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {dds_ad9767_tb_wave.do}

view wave
view structure
view signals

do {dds_ad9767_tb.udo}

run 1000ns
