######################################################################
#
# File name : UART_RAM_TFT_tb.udo
# Created on: Mon Mar 13 09:44:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
