# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
# IP: The module: 'system_rst_ps7_0_50M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
# IP: The module: 'system_rst_ps7_0_50M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NEW/TYUT/FPGA/Code/1_Learning/PS/1_BronzeDivision/axi_gpio/axi_gpio.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
