set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_BLK]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN L5 [get_ports Clk]
set_property PACKAGE_PIN M1 [get_ports VGA_CLK]
set_property PACKAGE_PIN P1 [get_ports VGA_VS]
set_property PACKAGE_PIN J5 [get_ports {VGA_RGB[13]}]
set_property PACKAGE_PIN K3 [get_ports {VGA_RGB[12]}]

set_property PACKAGE_PIN L4 [get_ports {VGA_RGB[9]}]
set_property PACKAGE_PIN R8 [get_ports {VGA_RGB[8]}]
set_property PACKAGE_PIN J6 [get_ports {VGA_RGB[7]}]
set_property PACKAGE_PIN J7 [get_ports {VGA_RGB[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports TFT_BL]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]

set_property PACKAGE_PIN R4 [get_ports Reset_n]
set_property PACKAGE_PIN W18 [get_ports uart_rx]
set_property PACKAGE_PIN P5 [get_ports TFT_BL]
set_property PACKAGE_PIN P6 [get_ports VGA_BLK]
set_property PACKAGE_PIN N1 [get_ports VGA_HS]
set_property PACKAGE_PIN M4 [get_ports {VGA_RGB[15]}]
set_property PACKAGE_PIN K5 [get_ports {VGA_RGB[14]}]
set_property PACKAGE_PIN K4 [get_ports {VGA_RGB[11]}]
set_property PACKAGE_PIN H8 [get_ports {VGA_RGB[10]}]
set_property PACKAGE_PIN M3 [get_ports {VGA_RGB[5]}]
set_property PACKAGE_PIN M2 [get_ports {VGA_RGB[4]}]
set_property PACKAGE_PIN L1 [get_ports {VGA_RGB[3]}]
set_property PACKAGE_PIN L2 [get_ports {VGA_RGB[2]}]
set_property PACKAGE_PIN J1 [get_ports {VGA_RGB[1]}]
set_property PACKAGE_PIN J2 [get_ports {VGA_RGB[0]}]

