######################################################################
#
# File name : UART_RAM_TFT_tb_wave.do
# Created on: Mon Mar 13 09:44:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
