######################################################################
#
# File name : UART_RAM_TFT_tb_simulate.do
# Created on: Mon Mar 20 16:18:51 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.UART_RAM_TFT_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {UART_RAM_TFT_tb_wave.do}

view wave
view structure
view signals

do {UART_RAM_TFT_tb.udo}

run 1000ns
