######################################################################
#
# File name : UART_RAM_TFT_tb_compile.do
# Created on: Mon Mar 20 16:18:50 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim_dlx64_10.6c\\win64pe\\vlib modelsim_lib/work
D:\\modelsim_dlx64_10.6c\\win64pe\\vlib modelsim_lib/msim

D:\\modelsim_dlx64_10.6c\\win64pe\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_dlx64_10.6c\\win64pe\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_dlx64_10.6c\\win64pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../UART_RAM_TFT.srcs/sources_1/ip/MMCM" \
"../../../../UART_RAM_TFT.srcs/sources_1/ip/RAM/sim/RAM.v" \
"../../../../UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM_clk_wiz.v" \
"../../../../UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM.v" \
"../../../../UART_RAM_TFT.srcs/sources_1/new/UART_RAM_TFT.v" \
"../../../../UART_RAM_TFT.srcs/sources_1/new/VGA_CTRL.v" \
"../../../../UART_RAM_TFT.srcs/sources_1/new/img_rx_wr.v" \
"../../../../UART_RAM_TFT.srcs/sources_1/new/uart_byte_rx.v" \
"../../../../UART_RAM_TFT.srcs/sim_1/new/UART_RAM_TFT_tb.v" \


# compile glbl module
D:\\modelsim_dlx64_10.6c\\win64pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

